version: 2
jobs:
  test-py3-tfcpu:

    environment:
      - CC_TEST_REPORTER_ID: 97d605718cc9bbe630ee773a4e8b49df32e87616185740c315b7118d59996502

    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-1-dependencies-py3-{{ checksum "test-requirements.txt" }}-{{ checksum "requirements.txt" }}
            - v1-1-dependencies-py3-

      - run: 
          name: make local tools executable
          command: |
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: install dependencies
          command: |
            pip install --quiet --user -r test-requirements.txt

      - run:
          name: cache by running test_datasets.py
          command: |
            py.test safeai/tests/test_datasets.py

      - save_cache:
          key: v1-1-dependencies-py3-{{ checksum "requirements.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      - run:
          name: run tests
          command: |
            python -m unittest discover
            ./cc-test-reporter before-build
            py.test safeai/tests --cov-report=xml:coverage.xml --cov=safeai
            ./cc-test-reporter after-build -t coverage.py coverage.xml

  test-py2-tfcpu:

    environment:
      - CC_TEST_REPORTER_ID: 97d605718cc9bbe630ee773a4e8b49df32e87616185740c315b7118d59996502

    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-1-dependencies-py2-{{ checksum "test-requirements.txt" }}-{{ checksum "requirements.txt" }}
            - v1-1-dependencies-py2-

      - run: 
          name: make local tools executable
          command: |
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: install dependencies
          command: |
            pip install --quiet --user -r test-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-1-dependencies-py2-{{ checksum "requirements.txt" }}-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            python -m unittest discover
            ./cc-test-reporter before-build
            py.test safeai/tests --cov-report=xml:coverage.xml --cov=safeai
            ./cc-test-reporter after-build -t coverage.py coverage.xml

workflows:
  version: 2
  test:
    jobs:
      - test-py3-tfcpu
      - test-py2-tfcpu
